### ISSUE TITLE
Incompatibility with CRAN version of pillar

### ISSUE THREAD

**Issue by krlmlr** [nbenn/prt#4]
Printing moves from tibble to pillar, including new options for customization. Some very raw and technical documentation is at https://pillar.r-lib.org/dev/articles/customization.html.

Tests now break if the development version of pillar is installed.

**Comment by nbenn** [comment]
Thanks for the heads up. Do you have a rough eta on when pillar v1.5 (?) might hit CRAN?

**Comment by krlmlr** [comment]
Soon-ish, next week or the week after next?

**Comment by krlmlr** [comment]
Wrapping up pillar 1.5.0. Do you want to release an update before, or wait until pillar hits CRAN?

**Comment by krlmlr** [comment]
Releasing very soon. https://pillar.r-lib.org/dev/articles/extending.html#body-1 has an example that should help you get started.

**Comment by krlmlr** [comment]
pillar 1.5.0 on CRAN now.

**Comment by nbenn** [comment]
@krlmlr Thanks for keeping me in the loop re pillar compatibility. I submitted an update to CRAN yesterday resolving the 1.5 compatibility issue. I appreciate the effort that went into making printing more customizable and the functionality demonstrated unter ['Tweak pillar composition'](https://pillar.r-lib.org/articles/extending.html#tweak-pillar-composition) really makes for interesting possibilities.

One thing that currently is missing for my use is a way of controlling `rowid` aspects. For my printing, I currently am doing a 'data.table' style approach, where the first and last n rows are printed and for this I need control over what is displayed as `rowid` (currently yielding a messy implementation on my side). Maybe opening up pillar for arbitrary "metadata" columns could be something for v1.6?

Other metadata ideas, apart from row numbers, that come to mind include partition info (relevant for a package such as prt), or in a table where rows can be lazily be loaded into memory individually (not sure whether something like this exists), in-memory availability could be indicated, etc. Currently the only way of doing something like this (as far as I understand) is by adding the info as actual columns and using S3 classes to customize styling. But if multiple tiers are printed you'd want for these meta columns to be repeated (just as is the case with row numbers).

I'm happy to open an issue on over at the pillar repo if you feel there is merit in my suggestion.

**Comment by krlmlr** [comment]
Thanks. Yeah, the body is currently opaque, I see potential for a `tbl_format_rowid()` or `ctl_new_rowid_pillar()` generic to start opening things up. Let's discuss in pillar.
